import { BrowserWindow } from 'electron';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

function createManagerWindow() {
    const entryPath = MAIN_WINDOW_WEBPACK_ENTRY;
    const preloadPath = MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY;

    const managerWindow = new BrowserWindow({
        width: 800,
        height: 600,
        webPreferences: {
            preload: preloadPath,
            devTools: process.env.NODE_ENV === 'development',
        },
        show: false,
    });

    managerWindow.removeMenu();
    managerWindow.loadURL(entryPath);
    managerWindow.webContents.openDevTools();

    managerWindow.once('ready-to-show', () => {
        managerWindow.show();
    });

    return managerWindow;
}

export default createManagerWindow;
